### PR TITLE
EL-3579 - Migrate Repository

### PR DESCRIPTION
**Pull request by ashley-hunter**
- Moving repository contents
- Updated dependencies
- Removed dummy content (there were some potentially valid projects/organizations which I left in, these can be removed if we don't actually want them)

Let me know if there is anything else that needs done

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/MicroFocus_CI_microfocus.github.io_migrate-repo

### CODE REVIEW

**Comment by donna-marijne** [comment]
Can you add the CI URL here please and also send to Andy and Roland?

**Comment by ashley-hunter** [comment]
The build doesn't seem to produce a CI site? The url I believe should be:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/github-user_CI_microfocus.github.io_migrate-repo

The build did succeed, but I don't see any URL available in the console output:

https://jenkins.hpeswlab.net/job/SEPG/job/MicroFocus/job/MicroFocus~microfocus.github.io~migrate-repo~CI/5/console

**Comment by donna-marijne** [comment]
It's important that we have a CI process for this repo. Could you get this working please? Let me know if you get stuck.

**Comment by donna-marijne** [comment]
Make sure the .tgz file has content and the SEPG build is running the appropriate build steps.

**Comment by ashley-hunter** [comment]
CI Build now working, will share the link with Andy and Roland

**Comment by ashley-hunter** [comment]
Thanks, good suggestion. I have now changed to use the `ux-icon` component throughout the site and update documentation accordingly

**Pull request merged**
